### PR TITLE
Document the `accept` property

### LINKED ISSUE #32: Setting file format
With the default file picker, <input type='file'> you can specify the file formats accepted via the "accept" attribute. Is this a possible feature for emberx-file-input?

### PR DESCRIPTION
**Pull request by Robdel12**
This will fix #32

### CODE REVIEW

**Comment by cowboyd** [comment]
Looks like maybe the most recent version of the module loader isn't compatible with Ember 1.13? 
At what point do we drop support?

**Comment by Robdel12** [comment]
@cowboyd what's interesting is this happened randomly. There has to be a dep that changed???

**Comment by cowboyd** [comment]
Yeah, seems that way. loader.js maybe?

**Comment by Robdel12** [comment]
Hm, I can't replicate this locally.
image

This is after a nombom

**Pull request merged**
