### PR TITLE
adds test helpers for integration and unit tests

### PR DESCRIPTION
**Pull request by bauerjon**
Wasn't sure exactly how we wanted to test the new test helpers. Figured I would throw this up to get some feedback first. 

I could [expand on existing tests ](https://github.com/thefrontside/emberx-file-input/blob/master/tests/acceptance/x-file-input-test.js#L90-L97)to the use helper. Or test the helper separately.

How do you feel about the direction I took with this?

---

issue: https://github.com/thefrontside/emberx-file-input/issues/47

### CODE REVIEW

**Comment by bauerjon** [comment]
This works if any one is in a crunch and wants to use it. Just be warned that the interface for this may change by the time it gets merged in.

You can pull these changes down in your package.json like so

```
"emberx-file-input": "git://github.com/bauerjon/emberx-file-input#adds-testing-helper",
```

**Comment by Robdel12** [comment]
Hey @bauerjon thanks for doing this work! I know I've kinda been MIA a bit on this. I wanna dedicate some time for this. Probably tomorrow. 

 In the mean time it looks like the CI failures are related to JSHint. If we could get those cleaned up that'd be awesome.

Great work!

**Comment by bauerjon** [comment]
@Robdel12 updated the p.r. to fix the jshint failures. let me know what you feel next steps on this should be. thanks!

**Comment by bauerjon** [comment]
@Robdel12 doing some house cleaning with my open p.r.s. Any update on this? Thnx!

**Comment by Robdel12** [comment]
Looks like all the tests pass and I'm cool with it. Any objects @cowboyd?

**Comment by bauerjon** [comment]
@cowboyd any thoughts on if we can merge this in?

**Comment by Robdel12** [comment]
I'm going to merge it!

**Comment by cowboyd** [comment]
👍  and released to npm?

**Comment by Robdel12** [comment]
I haven't done that. I think master is failing

**Comment by bauerjon** [comment]
Looks like this is causing the failure

> Cannot find module 'babel-plugin-transform-es2015-block-scoping'

https://travis-ci.org/thefrontside/emberx-file-input/jobs/245134132

**Comment by Robdel12** [comment]
Yeah I tried to clean the cache out on travis and that didn't work. That's about all I can do on my end while at work since I can't push to github :/

**Comment by Robdel12** [comment]
Looks like it's because of ember data: https://github.com/emberjs/data/issues/5024


... do we even need ED in this addon??

**Pull request merged**
